### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by sajadghawami** [iamdustan/react-hardware#31]
Is this repo still being maintained? There hasn't been an update for 6 Months.

**Comment by testacode** [comment]
no?

**Comment by iamdustan** [comment]
sure?

**Comment by JMFURY** [comment]
Just found the library. Very cool. I plan to see if Function components and Hooks would be possible.

**Comment by iamdustan** [comment]
I accidentally started working on this last week upgrading to latest version with hooks 😀

**Comment by brntbeer** [comment]
> I accidentally started working on this last week upgrading to latest version with hooks 😀

I am subscribed by interest alone but if there's good first issues to get into (especially for documentation) I'd be interested in helping!

**Comment by iamdustan** [comment]
To prove that I started: #32

As may be apparent, I don’t actively work on any of my public things. I also don’t know anything about hardware so that’s a bit of a limiting factor, but the basic stuff should work. Any API design proposals for how to make things work and documentation that makes sense and whatever would be very much appreciated (and maybe even peer-pressure-interest me into more actively working on this)

**Comment by JMFURY** [comment]
Ditto to the above. 

I have some experience in hardware (failed start-up with Arduino + BLE).. I can solder and understand schematics & IO on a halfway decent level.

Would be really cool to wire up an Arduino with Bluetooth device running on Hooks 🤘  

Looking forward to helping any way possible as well

I'll take a look at the PR this weekend.

**Comment by iamdustan** [comment]
Anyone want to...[useHooks](https://github.com/iamdustan/react-hardware/pull/32/commits/808a6301c65fcb54234d5cdc0c62ee13f9301688)?

```
const FlashingLedHook = () => {
  const [value, setState] = React.useState(1);
  useInterval(() => setState(value === 0 ? 1 : 0), 1000);

  return <pin pin={13} value={value} mode={'OUTPUT'} />;
};
```
